/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static jframes.DBConnection.con;

/**
 *
 * @author Vidusha
 */
public final class ManageStudents extends javax.swing.JFrame {

    /**
     * Creates new form ManageBook
     */
    String studentName,course,branch;
    int studentId;
    DefaultTableModel model;
    
    public ManageStudents()  {
        initComponents();
        setStudentDetailsToTable();
    }

  //to set the student details into the table
public void setStudentDetailsToTable() {

try {
Class.forName("com.mysql.cj.jdbc.Driver");
con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagementsystem","root", "");
Statement st = con.createStatement ();
ResultSet rs = st.executeQuery("select * from student_details");

while(rs.next ()){
String studentId = rs.getString("student_id");
String studentName = rs.getString("name");
String course = rs.getString("course");
String branch = rs.getString("branch");

Object[] obj = {studentId, studentName, course, branch};
model = (DefaultTableModel) tbl_studentDetails.getModel ();
model .addRow (obj) ;
}
} catch (Exception e) {
e.printStackTrace();

}
}

//to add book to book details table
public boolean addStudent () {
boolean isAdded = false;
studentId = Integer.parseInt(txt_studentId.getText ());
studentName = txt_studentName.getText ();
course = jComboBox_course.getSelectedItem().toString();
branch = jComboBox_batch.getSelectedItem().toString();

try {
    Connection con = DBConnection.getConnection();
    String sql = "insert into student_details values(?,?,?,?)";
    PreparedStatement pst = con.prepareStatement (sql);
    pst.setInt(1, studentId);
    pst.setString(2, studentName) ;
    pst.setString(3, course);
    pst.setString(4, branch); 

    int rowCount = pst.executeUpdate ();
    if (rowCount > 0) {
    isAdded = true;
    }else{
    isAdded = false;
    }
} catch (Exception e) {
    e.printStackTrace ();
}
return isAdded; 
}

//to update book details

public boolean updateStudent () {
boolean isUpdated = false;
studentId = Integer.parseInt(txt_studentId.getText ());
studentName = txt_studentName.getText ();
course = jComboBox_course.getSelectedItem().toString();
branch = jComboBox_batch.getSelectedItem().toString();

try {
Connection con = DBConnection.getConnection();
String sql = "update student_details set name = ?,course = ?,branch = ? where student_id = ?";
PreparedStatement pst = con.prepareStatement (sql); 
pst.setString(1, studentName);
pst.setString(2, course);
pst.setString(3, branch);
pst.setInt(4, studentId);

int rowCount = pst.executeUpdate ();
if (rowCount > 0) {
    isUpdated = true;
}else{
    isUpdated = false;
}
} catch (Exception e) {
     e.printStackTrace();  
}
return isUpdated;
}

//method to delete student detail
public boolean deleteStudent () {
boolean isDeleted = false;
studentId = Integer.parseInt (txt_studentId.getText ());

try {
Connection con = DBConnection.getConnection();
String sql = "delete from student_details where student_id = ? ";
PreparedStatement pst = con.prepareStatement (sql);
pst.setInt(1, studentId);

int rowCount = pst.executeUpdate();
if (rowCount > 0) {

    isDeleted = true;
}else{
    isDeleted = false;
}
} catch (Exception e) {

e.printStackTrace();
}

return isDeleted;
}

//method to clear table
public void clearTable(){
    DefaultTableModel model = (DefaultTableModel) tbl_studentDetails.getModel();
    model.setRowCount(0);
}
    //to set the book details into the table

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_studentId = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_studentName = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        delete_btn = new rojerusan.RSMaterialButtonCircle();
        add_btn = new rojerusan.RSMaterialButtonCircle();
        update_btn = new rojerusan.RSMaterialButtonCircle();
        jComboBox_batch = new javax.swing.JComboBox<String>();
        jComboBox_course = new javax.swing.JComboBox<String>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_studentDetails = new rojeru_san.complementos.RSTableMetro();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidusha\\Desktop\\New folder (4)\\JAVA\\resoures\\AddNewBookIcons\\back.png")); // NOI18N
        jLabel1.setText(" BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 46));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        txt_studentId.setBackground(new java.awt.Color(255, 153, 51));
        txt_studentId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_studentId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_studentId.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        txt_studentId.setPhColor(new java.awt.Color(255, 255, 255));
        txt_studentId.setPlaceholder("Enter Student Id.....");
        txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentIdFocusLost(evt);
            }
        });
        jPanel1.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 172, 260, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Student Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 200, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidusha\\Desktop\\New folder (4)\\JAVA\\resoures\\AddNewBookIcons\\BookID.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 164, 50, 50));

        txt_studentName.setBackground(new java.awt.Color(255, 153, 51));
        txt_studentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_studentName.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_studentName.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        txt_studentName.setPhColor(new java.awt.Color(255, 255, 255));
        txt_studentName.setPlaceholder("Enter Student Name.....");
        txt_studentName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentNameFocusLost(evt);
            }
        });
        jPanel1.add(txt_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 307, 260, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Student Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 272, 260, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidusha\\Desktop\\New folder (4)\\JAVA\\resoures\\AddNewBookIcons\\Book Name.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, 50, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Select Course ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 392, 190, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidusha\\Desktop\\New folder (4)\\JAVA\\resoures\\AddNewBookIcons\\Author.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 405, 50, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Select Batch No");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 210, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidusha\\Desktop\\New folder (4)\\JAVA\\resoures\\AddNewBookIcons\\Quentity.png")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 535, 50, 50));

        delete_btn.setBackground(new java.awt.Color(255, 0, 51));
        delete_btn.setBorder(null);
        delete_btn.setText("DELETE");
        delete_btn.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 655, 130, 70));

        add_btn.setBackground(new java.awt.Color(255, 0, 51));
        add_btn.setBorder(null);
        add_btn.setText("ADD");
        add_btn.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 655, 130, 70));

        update_btn.setBackground(new java.awt.Color(51, 51, 255));
        update_btn.setBorder(null);
        update_btn.setText("UPDATE");
        update_btn.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 655, 130, 70));

        jComboBox_batch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jComboBox_batch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Batch No", "Batch 06", "Batch 07", "Batch 08", "Batch 09", "Batch 10", "Batch 11" }));
        jComboBox_batch.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox_batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_batchActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 260, 40));

        jComboBox_course.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jComboBox_course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Course", "Faculty of IT", "Faculty of Education", "Faculty of Management", "Faculty of Science", "Faculty of Law", "Faculty of Technology" }));
        jComboBox_course.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_courseActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));

        tbl_studentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Name", "Course", "Branch"
            }
        ));
        tbl_studentDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_studentDetails.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tbl_studentDetails.setRowHeight(40);
        tbl_studentDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_studentDetails);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 940, 220));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 51));
        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidusha\\Desktop\\New folder (4)\\JAVA\\resoures\\AddNewBookIcons\\icons8_Student_Male_100px.png")); // NOI18N
        jLabel26.setText("Manage Students ");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 470, 100));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidusha\\Desktop\\New folder (4)\\JAVA\\resoures\\icons\\undraw_building_websites_i78t.png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 930, 700));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 1010, 800));

        setSize(new java.awt.Dimension(1500, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void txt_studentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIdFocusLost

    }//GEN-LAST:event_txt_studentIdFocusLost

    private void txt_studentNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentNameFocusLost

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        if(deleteStudent()== true){
           JOptionPane.showMessageDialog(this,"Student Deleted");
           clearTable();
           setStudentDetailsToTable();
       } else{
           JOptionPane.showMessageDialog(this,"Student Deletion Failed"); }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
       if(addStudent()== true){
           JOptionPane.showMessageDialog(this,"Student Added");
           clearTable();
           setStudentDetailsToTable();
       } else{
           JOptionPane.showMessageDialog(this,"Student Addition Failed"); }
    }//GEN-LAST:event_add_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
             if(updateStudent() == true){
           JOptionPane.showMessageDialog(this,"Student Updated");
           clearTable();
           setStudentDetailsToTable();
       } else{
           JOptionPane.showMessageDialog(this,"Student Updation Failed"); }
    }//GEN-LAST:event_update_btnActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tbl_studentDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentDetailsMouseClicked
     int rowNo = tbl_studentDetails.getSelectedRow();
    TableModel model = tbl_studentDetails.getModel ();

    txt_studentId.setText(model.getValueAt (rowNo, 0).toString()); 
    txt_studentName.setText(model.getValueAt (rowNo, 1).toString());
    jComboBox_course.setSelectedItem(model.getValueAt (rowNo, 2).toString());
    jComboBox_batch.setSelectedItem(model.getValueAt (rowNo, 3).toString());
    }//GEN-LAST:event_tbl_studentDetailsMouseClicked

    private void jComboBox_batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_batchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_batchActionPerformed

    private void jComboBox_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_courseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle add_btn;
    private rojerusan.RSMaterialButtonCircle delete_btn;
    private javax.swing.JComboBox<String> jComboBox_batch;
    private javax.swing.JComboBox<String> jComboBox_course;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSTableMetro tbl_studentDetails;
    private app.bolivia.swing.JCTextField txt_studentId;
    private app.bolivia.swing.JCTextField txt_studentName;
    private rojerusan.RSMaterialButtonCircle update_btn;
    // End of variables declaration//GEN-END:variables



    
}
